coil_diameter: 100
world_box_size: 1000
calculateRLC: True
particles:
  part_type: 0 # Monopole
  start_point_x: -50
  start_point_y: -50
  start_point_z: -50
  direction_x: 1.
  direction_y: 1.
  direction_y: 1.
  speed:
    mean: 0.00001
    std: 0.0000000001
  electric_charge: 1
  magnetic_charge: 1
array_config:
  coil_diameter: 100
  coil_arrange_filename: '/Users/qinglin/WorkSpace/MonopoleProject/CoilSignalSim/raws/coil_arrange/single_coil_array.pkl'
field_config:
  num_coil_turns: 100
  filename: '/Users/qinglin/WorkSpace/MonopoleProject/CoilSignalSim/outputs/field_generators/monopole.pkl'
noise_config:
  R:  1.0
  T:  300
circuit_config:
  placeholder: True

