coil_diameter: 100
world_box_size: 1000
particles:
  part_type: 0 # Monopole
  start_point_r: 500
  start_point_theta: 3.141592653
  start_point_phi: 0
  direction_theta: 0
  direction_phi: 0
  speed:
    mean: 0.00001
    std: 0.0000000001
  electric_charge: 1
  magnetic_charge: 1
array_config:
  coil_diameter: 100
  coil_arrange_filename: '/Users/qinglin/WorkSpace/MonopoleProject/CoilSignalSim/raws/coil_arrange/single_coil_array.pkl'
field_config:
  num_coil_turns: 100
  filename: '/Users/qinglin/WorkSpace/MonopoleProject/CoilSignalSim/outputs/field_generators/monopole.pkl'
noise_config:
  R:  1.0
  T:  0
