world_box_size: 500
cell_step: 5.0
particle_step: 5.0
verbose: False
save_E: False
particles:
  part_type: 2
  speed: 0.001
  electric_charge: 1
  magnetic_charge: 1
  magnetic_moment: [9.284e-24,0,0] # Magnetic moment of an electron, pointing to Z+