coil_diameter: 100
num_coil_turns: 100
world_box_size: 200
cell_step: 2.0
particle_step: 2.0
verbose: True
particles:
  part_type: 1 # Charged Particle
  start_point_type: 'point'
  start_x: 0.0
  start_y: 0.0
  start_z: 0.0
  direction_type: 'fixed'
  direction_x: 1.0
  direction_y: 0.0
  direction_z: 0.0
  speed_type: 'fixed'
  speed: 0.01
  moment_tupe: 'fixed'
  magnetic_moment: [0,0,9.284e-24] # Magnetic moment of an electron, pointing to Z+
